### ISSUE TITLE
你的  插件广播  确定可以  正常启动 吗？

### ISSUE THREAD

**Issue by laopaoerdudu** [13767004362/HookDemo#1]
W/System.err: java.lang.ClassCastException: android.content.pm.PackageParser$Activity cannot be cast to android.app.Activity

**Comment by 13767004362** [comment]
> W/System.err: java.lang.ClassCastException: android.content.pm.PackageParser$Activity cannot be cast to android.app.Activity


你的代码存在类型转换的问题，需要修改。

PackageParser中静态内部类Activity 是一个实体类，非组件Activity
```
 public final static class Activity extends Component<ActivityIntentInfo> implements Parcelable {
        @UnsupportedAppUsage
        public final ActivityInfo info;
        private boolean mHasMaxAspectRatio;
        private boolean mHasMinAspectRatio;
}
```
更多详细信息，请阅读[PackageParser源码](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/content/pm/PackageParser.java;l=154;drc=master?q=PackageParser&sq=&ss=android%2Fplatform%2Fsuperproject)
